import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { GetUsersDocument, useGetUsersQuery, User } from '../generated/graphql'
import { addApolloState, initializeApollo } from '../lib/apolloClient'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { data, loading } = useGetUsersQuery()

  if (loading) return <h1>Loading...</h1>
  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Manage user</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: 'flex',
          width: '800px',
          margin: '0 auto',
          boxShadow: 'rgba(0, 0, 0, 0.35) 0px 5px 15px',
          minHeight: 600,
          gap: 30,
        }}
      >
        {data?.users?.map((user: User | null) => (
          <div key={user?.id} style={{ fontSize: 12, textAlign: 'center' }}>
            <Image src="/avatar.jpg" alt="avatar" width={100} height={100} style={{ borderRadius: '50%' }} />
            <p>Name: {user?.name}</p>
            <p>Age: {user?.age}</p>
            <p>Email: {user?.email}</p>
            <p>Position: {user?.isAdmin ? 'Leader' : 'Member'}</p>
            <button>
              <Link href={`/user/${user?.id}`}>
                <a>Update</a>
              </Link>
            </button>
          </div>
        ))}
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const apolloClient = initializeApollo()

  await apolloClient.query({
    query: GetUsersDocument,
  })

  return addApolloState(apolloClient, {
    props: {},
  })
}

export default Home
